# Generated by Django 4.0.4 on 2022-07-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=50)),
                ('imagenes', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
